package com.example.waz.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.waz.UI.Bean.MyBean;

import com.example.waz.dao.MyBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myBeanDaoConfig;

    private final MyBeanDao myBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myBeanDaoConfig = daoConfigMap.get(MyBeanDao.class).clone();
        myBeanDaoConfig.initIdentityScope(type);

        myBeanDao = new MyBeanDao(myBeanDaoConfig, this);

        registerDao(MyBean.class, myBeanDao);
    }
    
    public void clear() {
        myBeanDaoConfig.clearIdentityScope();
    }

    public MyBeanDao getMyBeanDao() {
        return myBeanDao;
    }

}
